export const SORT_PRICE_UP = 'SORT_PRICE_UP';
export const SORT_PRICE_DOWN = 'SORT_PRICE_DOWN';
export const GET_BOOKS_FROM_SERVER = "GET_BOOKS_FROM_SERVER";
export const RANDOM = "RANDOM";
export const SELECTED_BOOKS_FILTER = 'SELECTED_BOOKS_FILTER';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';

//vinted
export const GET_NEWS_FROM_SERVER = 'GET_NEWS_FROM_SERVER';
export const ADD_PRODUCT_FROM_SERVER = 'ADD_PRODUCT_FROM_SERVER';
