import goldFactoryImage from '../images/buildings/smithy 1.svg';
import millImage from '../images/buildings/mill 1.svg';
import treeImage from '../images/buildings/tree 1.svg';
import stoneMineImage from '../images/buildings/mine1.svg';

const allBuildings = [
    {
        id: 1,
        level: 0,
        name: 'Gold factory',
        desc1: 'This building produces gold',
        desc2: 'Produces gold',
        shortName: 'gold',
        image: goldFactoryImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '213',
            '325',
            '432',
            '547',
            '652',
            '762',
        ],
        woodNeeded: [
            '100',
            '232',
            '342',
            '457',
            '567',
            '676',
            '782',
        ],
        goldNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        stoneNeeded: [
            '100',
            '228',
            '333',
            '442',
            '552',
            '664',
            '775',
        ],
        workersNeeded: [
            '1',
            '5',
            '10',
            '15',
            '20',
            '25',
            '30',
        ]
    },
    {
        id: 2,
        level: 0,
        name: 'Mill',
        desc1: 'This building produces food',
        desc2: 'Produces food',
        shortName: 'food',
        image: millImage,
        //resourcesNeeded
        foodNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        woodNeeded: [
            '100',
            '213',
            '322',
            '438',
            '544',
            '656',
            '767',
        ],
        goldNeeded: [
            '100',
            '223',
            '338',
            '445',
            '553',
            '664',
            '777',
        ],
        stoneNeeded: [
            '100',
            '201',
            '324',
            '436',
            '545',
            '651',
            '769',
        ],
        workersNeeded: [
            '1',
            '5',
            '10',
            '15',
            '20',
            '25',
            '30',
        ]
    },
    {
        id: 3,
        level: 0,
        name: 'Forest',
        desc1: 'This building produces timber',
        desc2: 'Produces timber',
        shortName: 'wood',
        image: treeImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '222',
            '334',
            '442',
            '558',
            '662',
            '772',
        ],
        woodNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        goldNeeded: [
            '100',
            '224',
            '332',
            '442',
            '552',
            '666',
            '778',
        ],
        stoneNeeded: [
            '100',
            '232',
            '345',
            '468',
            '578',
            '686',
            '790',
        ],
        workersNeeded: [
            '1',
            '5',
            '10',
            '15',
            '20',
            '25',
            '30',
        ]
    },
    {
        id: 4,
        level: 0,
        name: 'Stone Mine',
        desc1: 'This building produces stone',
        desc2: 'Produces stone',
        shortName: 'stone',
        image: stoneMineImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '212',
            '323',
            '448',
            '558',
            '669',
            '772',
        ],
        woodNeeded: [
            '100',
            '231',
            '345',
            '452',
            '562',
            '675',
            '789',
        ],
        goldNeeded: [
            '100',
            '210',
            '323',
            '438',
            '545',
            '658',
            '762',
        ],
        stoneNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        workersNeeded: [
            '1',
            '5',
            '10',
            '15',
            '20',
            '25',
            '30',
        ]
    },

]

export default allBuildings;