import goldFactoryImage from '../images/buildings/smithy 1.svg';
import millImage from '../images/buildings/mill 1.svg';
import treeImage from '../images/buildings/tree 1.svg';
import workerImage from '../images/resources/worker.png';
import stoneMineImage from '../images/buildings/mine1.svg';

const allBuildings = [
    {
        id: 1,
        level: 0,
        name: 'Gold factory',
        desc1: 'This building produces gold',
        desc2: 'Produces gold',
        shortName: 'gold',
        image: goldFactoryImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        woodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        goldNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        stoneNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        workersNeeded: [
            '10',
            '20',
            '30',
            '40',
            '50',
            '60',
            '70',
        ]
    },
    {
        id: 2,
        level: 0,
        name: 'Mill',
        desc1: 'This building produces food',
        desc2: 'Produces food',
        shortName: 'food',
        image: millImage,
        //resourcesNeeded
        foodNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        woodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        goldNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        stoneNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        workersNeeded: [
            '10',
            '20',
            '30',
            '40',
            '50',
            '60',
            '70',
        ]
    },
    {
        id: 3,
        level: 0,
        name: 'Forest',
        desc1: 'This building produces timber',
        desc2: 'Produces timber',
        shortName: 'wood',
        image: treeImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        woodNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        goldNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        stoneNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        workersNeeded: [
            '10',
            '20',
            '30',
            '40',
            '50',
            '60',
            '70',
        ]
    },
    {
        id: 4,
        level: 0,
        name: 'Stone Mine',
        desc1: 'This building produces stone',
        desc2: 'Produces stone',
        shortName: 'stone',
        image: stoneMineImage,
        //resourcesNeeded
        foodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        woodNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        goldNeeded: [
            '100',
            '200',
            '300',
            '400',
            '500',
            '600',
            '700',
        ],
        stoneNeeded: [
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
            '0',
        ],
        workersNeeded: [
            '10',
            '20',
            '30',
            '40',
            '50',
            '60',
            '70',
        ]
    },

]

export default allBuildings;